"""AE17 Meta-Model / Stacking Layer substrate.

Deterministic rule-based meta shadow combinator over AE16 outputs.
Does NOT train second-stage ML models. Research/shadow only.
"""

from __future__ import annotations

PHASE = "AE17"
META_MODE = "rule_based_meta_shadow"
AUTHORITY_STATUS = "AE17_RESEARCH_SHADOW_ONLY"
META_ENGINE_VERSION = "ae17_meta_stacking_v1"

CLASSIFICATION_PASS = "AE17_META_STACKING_LAYER_PASS_WITH_SHADOW_OUTPUTS"
CLASSIFICATION_PASS_LIMITATIONS = "AE17_META_STACKING_LAYER_PASS_WITH_LIMITATIONS"
CLASSIFICATION_MISSING_AE16 = "AE17_BLOCKED_MISSING_AE16_INPUTS"
CLASSIFICATION_FEATURE_PARITY = "AE17_BLOCKED_FEATURE_PARITY_GAP"
CLASSIFICATION_LOOKAHEAD = "AE17_BLOCKED_LOOKAHEAD_CONTAMINATION"
CLASSIFICATION_LINEAGE = "AE17_BLOCKED_LINEAGE_GAP"
CLASSIFICATION_AUTHORITY = "AE17_BLOCKED_AUTHORITY_ESCALATION"

__all__ = [
    "PHASE",
    "META_MODE",
    "AUTHORITY_STATUS",
    "META_ENGINE_VERSION",
    "CLASSIFICATION_PASS",
    "CLASSIFICATION_PASS_LIMITATIONS",
    "CLASSIFICATION_MISSING_AE16",
    "CLASSIFICATION_FEATURE_PARITY",
    "CLASSIFICATION_LOOKAHEAD",
    "CLASSIFICATION_LINEAGE",
    "CLASSIFICATION_AUTHORITY",
]
