"""Unified candidate schema package (Phase E2)."""

from app.candidates.examples import (
    make_all3_candidate_example,
    make_minimal_candidate_example,
    make_research_rejected_candidate_example,
    make_tab_rf_candidate_example,
)
from app.candidates.schema import (
    SCHEMA_VERSION,
    ArtifactLineage,
    CandidateDecisionState,
    CandidateIdentity,
    ConsensusTier,
    DecisionStatus,
    EnrichmentState,
    EnrichmentStatus,
    ExitPolicyContext,
    LLMReviewState,
    LLMReviewStatus,
    MarketContext,
    ModelScores,
    UnifiedCandidate,
    compute_candidate_id,
    infer_consensus_tier,
    utc_now_iso,
)
from app.candidates.serialization import (
    candidate_from_dict,
    candidate_from_flat_dict,
    candidate_from_json,
    candidate_to_dict,
    candidate_to_flat_dict,
    candidate_to_json,
    normalize_flat_value_for_export,
    normalize_flat_value_for_import,
)
from app.candidates.validation import (
    compute_vote_count,
    is_finite_number,
    is_syntactically_valid_artifact_id,
    normalize_event_timestamp,
    normalize_pair_address,
    validate_finite_numeric,
)

__all__ = [
    "SCHEMA_VERSION",
    "ArtifactLineage",
    "CandidateDecisionState",
    "CandidateIdentity",
    "ConsensusTier",
    "DecisionStatus",
    "EnrichmentState",
    "EnrichmentStatus",
    "ExitPolicyContext",
    "LLMReviewState",
    "LLMReviewStatus",
    "MarketContext",
    "ModelScores",
    "UnifiedCandidate",
    "candidate_from_dict",
    "candidate_from_flat_dict",
    "candidate_from_json",
    "candidate_to_dict",
    "candidate_to_flat_dict",
    "candidate_to_json",
    "compute_candidate_id",
    "compute_vote_count",
    "infer_consensus_tier",
    "is_finite_number",
    "is_syntactically_valid_artifact_id",
    "make_all3_candidate_example",
    "make_minimal_candidate_example",
    "make_research_rejected_candidate_example",
    "make_tab_rf_candidate_example",
    "normalize_event_timestamp",
    "normalize_flat_value_for_export",
    "normalize_flat_value_for_import",
    "normalize_pair_address",
    "utc_now_iso",
    "validate_finite_numeric",
]
